/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inicial.pomodoro.view.fragment;

/**
 *
 * @author myhouse
 */
public class CardActionTableTarefa extends javax.swing.JPanel {

    /**
     * Creates new form CardActionTableTarefa
     */
    public CardActionTableTarefa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(102, 25));
        setPreferredSize(new java.awt.Dimension(102, 25));
        setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Editar");
        add(jButton1, new java.awt.GridBagConstraints());

        jButton2.setText("Apagar");
        add(jButton2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
