/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inicial.pomodoro.view;

import com.inicial.pomodoro.model.ConfigCronometroEvent;


/**
 *
 * @author myhouse
 */
public class ConfigCronometroPanel extends javax.swing.JPanel {
    
    private ConfigCronometroEvent configCronometroEvent;
    
    private int valueTarefa = 25;
    private int valuePausa = 5;
    private int valuePausaLonga = 30;
    
    private final String[] tarefaValues = new String[]{"5","10","15","20","25","30","35","40","50","60"};
    private final String[] pausaValues = new String[]{"5","10","15","20","25","30","35","40","50","60"};
    private final String[] pausaLongaValues = new String[]{"10","15","20","25","30","40","50","60"};

    /**
     * Creates new form ConfigCronometroPanel
     */
    public ConfigCronometroPanel() {        
        initComponents();
    }
    
    public void addListener(ConfigCronometroEvent configCronometroEvent) {
        this.configCronometroEvent = configCronometroEvent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectPausa = new javax.swing.JComboBox<>();
        selectPausaLonga = new javax.swing.JComboBox<>();
        selectTarefa = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("Configurações");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel2.setText("Tarefa");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel3.setText("Pause Longa");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel4.setText("Pausa");

        selectPausa.setModel(new javax.swing.DefaultComboBoxModel<>(pausaValues));
        selectPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPausaActionPerformed(evt);
            }
        });
        selectPausa.setSelectedItem(String.valueOf(valuePausa));

        selectPausaLonga.setModel(new javax.swing.DefaultComboBoxModel<>(pausaLongaValues));
        selectPausaLonga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPausaLongaActionPerformed(evt);
            }
        });
        selectPausaLonga.setSelectedItem(String.valueOf(valuePausaLonga));

        selectTarefa.setModel(new javax.swing.DefaultComboBoxModel<>(tarefaValues));
        selectTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTarefaActionPerformed(evt);
            }
        });
        selectTarefa.setSelectedItem(String.valueOf(valueTarefa));

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)
                                .addComponent(selectTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectPausaLonga, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(selectPausaLonga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectPausa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(selectTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(btnSave))
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void selectPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPausaActionPerformed
        int valor = Integer.parseInt( (String) selectPausa.getSelectedItem() );
        valuePausa = valor;
    }//GEN-LAST:event_selectPausaActionPerformed

    private void selectTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTarefaActionPerformed
        int valor = Integer.parseInt( (String) selectTarefa.getSelectedItem() );
        valueTarefa = valor;
    }//GEN-LAST:event_selectTarefaActionPerformed

    private void selectPausaLongaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPausaLongaActionPerformed
        int valor = Integer.parseInt( (String) selectPausaLonga.getSelectedItem() );
        valuePausaLonga = valor;
    }//GEN-LAST:event_selectPausaLongaActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        onSave();
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void onSave() {
        if(configCronometroEvent!=null)
            configCronometroEvent.onSave(valueTarefa, valuePausa, valuePausaLonga);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> selectPausa;
    private javax.swing.JComboBox<String> selectPausaLonga;
    private javax.swing.JComboBox<String> selectTarefa;
    // End of variables declaration//GEN-END:variables
}
