/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inicial.pomodoro.view;

import com.inicial.pomodoro.model.ConfigCronometroEvent;
import com.inicial.pomodoro.model.CronometroEvent;
//import com.inicial.pomodoro.model.LongPauseSound;
import com.inicial.pomodoro.model.NotificationSound;
//import com.inicial.pomodoro.model.PauseSound;
import com.inicial.pomodoro.model.Step;
import com.inicial.pomodoro.model.StepEventInterface;
import com.inicial.pomodoro.model.StepInterface;
//import com.inicial.pomodoro.model.StepSound;
import com.inicial.pomodoro.model.TimeEventInterface;
import com.inicial.pomodoro.model.Timer;
import com.inicial.pomodoro.model.TimerInterface;
import com.inicial.pomodoro.model.icon.MaterializeIconFactory;
import java.awt.event.WindowAdapter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author myhouse
 */
public class CronometroPanel extends javax.swing.JPanel {
    
    private TimerInterface cronometro;
    private StepInterface step;
    private CronometroEvent cronometroEvent;
    
    private boolean stepPlayed = true;
    private boolean stepPaused = false;
    private boolean stepLongPaused = false;
    
    public static int TIMESTEP = 25;
    public static int TIMEPAUSE = 5;
    public static int TIMELONGPAUSE = 30;
    
    private int MINUTE = 60;
    
    /**
     * Creates new form CronometroView
     */
    public CronometroPanel(){
        initComponents();
        step = new Step();
        step.setNumber(lbStepNumber);
        step.setStatus(lbStepStatus);
        step.addListener(stepEventListener());
    }
    
    public void addCronometroListener(CronometroEvent cronometroEvent) {
        this.cronometroEvent = cronometroEvent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showTimer = new javax.swing.JLabel();
        btnPlayPause = new javax.swing.JButton(getIcon("play"));
        btnStop = new javax.swing.JButton(getIcon("stop"));
        btnNextStep = new javax.swing.JButton(getIcon("next"));
        lbStepNumber = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton(getIcon("refresh"));
        lbStepStatus = new javax.swing.JLabel();
        stepProgress = new javax.swing.JProgressBar();
        btnConfigCronometro = new javax.swing.JButton(getIcon("setting"));
        lbTimerStep = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbTimerPause = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTimerLongPause = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        showTimer.setFont(new java.awt.Font("DejaVu Sans", 1, 80)); // NOI18N
        showTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showTimer.setText("00:00");

        btnPlayPause.setText("");
        btnPlayPause.setToolTipText("Play/Pause");
        btnPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPauseActionPerformed(evt);
            }
        });

        btnStop.setText("");
        btnStop.setToolTipText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnNextStep.setText("");
        btnNextStep.setToolTipText("Next");
        btnNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextStepActionPerformed(evt);
            }
        });

        lbStepNumber.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lbStepNumber.setText("1");

        btnReset.setText("");
        btnReset.setToolTipText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lbStepStatus.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        lbStepStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStepStatus.setText("Step");
        lbStepStatus.setToolTipText("");
        lbStepStatus.setFocusTraversalPolicyProvider(true);

        stepProgress.setMaximum(4);
        stepProgress.setValue(1);
        stepProgress.setMaximumSize(new java.awt.Dimension(10, 20));
        stepProgress.setPreferredSize(new java.awt.Dimension(10, 20));

        btnConfigCronometro.setText("");
        btnConfigCronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigCronometroActionPerformed(evt);
            }
        });

        lbTimerStep.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lbTimerStep.setText("25");
        lbTimerStep.setToolTipText("Tarefa");

        jLabel2.setText("/");

        lbTimerPause.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lbTimerPause.setText("5");
        lbTimerPause.setToolTipText("Pausa");

        jLabel4.setText("/");

        lbTimerLongPause.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lbTimerLongPause.setText("30");
        lbTimerLongPause.setToolTipText("Longa Pausa");

        jLabel1.setText("T");

        jLabel3.setText("P");

        jLabel5.setText("LP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(stepProgress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextStep, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnConfigCronometro)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTimerStep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTimerPause)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTimerLongPause)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbStepStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbStepNumber))
                            .addComponent(showTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnConfigCronometro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbStepStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTimerStep)
                        .addComponent(jLabel2)
                        .addComponent(lbTimerPause)
                        .addComponent(jLabel4)
                        .addComponent(lbTimerLongPause)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5))
                    .addComponent(lbStepNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showTimer)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlayPause)
                    .addComponent(btnStop)
                    .addComponent(btnReset)
                    .addComponent(btnNextStep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextStepActionPerformed
        if(cronometro == null){
            JOptionPane.showMessageDialog(null, "É necessário iniciar o cronometro.");
            return;
        }
        
        if(stepPlayed) {
            cronometroEvent.onNextStep();
        }
        
        resetCronometro(cronometro, evt);
    }//GEN-LAST:event_btnNextStepActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if(cronometro == null){
            JOptionPane.showMessageDialog(null, "É necessário iniciar o cronometro.");
            return;
        }
        cronometro.stop();
        cronometro = null;
        this.btnPlayPause.setIcon(getIcon("play"));
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPauseActionPerformed
        if (cronometro == null) {
            cronometro = new Timer(this.showTimer);
            cronometro.addListener(cronometroEventListener(evt));
            cronometro.start();
            this.btnPlayPause.setIcon(getIcon("pause"));
        } else {
            if(cronometro.isPaused()) {
                cronometro.resume();
                this.btnPlayPause.setIcon(getIcon("pause"));
            }
            else {
                cronometro.pause();
                this.btnPlayPause.setIcon(getIcon("play"));
            }
        }
        
    }//GEN-LAST:event_btnPlayPauseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        if(cronometro == null){
            JOptionPane.showMessageDialog(null, "É necessário iniciar o cronometro.");
            return;
        }
        if(!cronometro.isPaused()) {
            btnPlayPauseActionPerformed(evt);
        }
        resetAll();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnConfigCronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigCronometroActionPerformed
        if(cronometro!=null&&!cronometro.isPaused()) {
            btnPlayPauseActionPerformed(evt);
        }
        
        ConfigCronometroFrame frame = ConfigCronometroFrame.init();
        frame.addConfigCronometroListener(new ConfigCronometroEvent() {
            @Override
            public void onSave(int tarefa, int pausa, int longaPausa) {
                TIMESTEP = tarefa;
                TIMEPAUSE = pausa;
                TIMELONGPAUSE = longaPausa;
                lbTimerStep.setText(String.valueOf(TIMESTEP));
                lbTimerPause.setText(String.valueOf(TIMEPAUSE));
                lbTimerLongPause.setText(String.valueOf(TIMELONGPAUSE));
                if(cronometro!=null&&cronometro.isPaused()) {
                    btnPlayPauseActionPerformed(evt);
                }
            }
        });
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if(cronometro!=null&&cronometro.isPaused()) {
                    btnPlayPauseActionPerformed(evt);
                }
                System.out.println("Fechou!");
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_btnConfigCronometroActionPerformed

    private TimeEventInterface cronometroEventListener(java.awt.event.ActionEvent evt) {
        return new TimeEventInterface() {
                @Override
                public void onChange(Timer timer, int contador) {
                    if (stepPaused) {
                        if(isPause(contador)) { 
                            new NotificationSound().reproduzir();
                            resetCronometro(timer, evt);
                        }
                    } else if(stepPlayed) {
                        if(isStep(contador)) {
                            new NotificationSound().reproduzir();
                            btnNextStepActionPerformed(evt);
                        }
                    } else if(stepLongPaused) {
                        if (isLongPause(contador)) {
                            new NotificationSound().reproduzir();
                            step.reset();
                        }
                    }
                }
            };
    }
    
    private StepEventInterface stepEventListener() {
        return new StepEventInterface() {
            @Override
            public void onChange(String status, int contStep, int contPause) {
                if(status.equals(Step.STEP)) {
                    changeValuesOfConfigCronometro(true, false, false);
                } else if(status.equals(Step.PAUSE)) {
                    changeValuesOfConfigCronometro(false, true, false);
                } else if(status.equals(Step.LONGPAUSE)) {
                    changeValuesOfConfigCronometro(false, false, true);
                }
                stepProgress.setValue(contStep+1);
            }
        };
    }
    
    private void resetCronometro(TimerInterface timer, java.awt.event.ActionEvent evt) {
        btnPlayPauseActionPerformed(evt);
        btnPlayPauseActionPerformed(evt);
        timer.reset();
        step.nextStep();
    }
    
    private void changeValuesOfConfigCronometro(boolean play, boolean pause, boolean longPause) {
        this.stepPlayed = play;
        this.stepPaused = pause;
        this.stepLongPaused = longPause;
    }
    
    private ImageIcon getIcon(String icon){
        try {
            return new MaterializeIconFactory().build(icon,20,20);
        } catch (IOException ex) {
            Logger.getLogger(CronometroPanel.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    
    private void resetAll() {
        cronometro.reset();
        step.reset();
        changeValuesOfConfigCronometro(true, false, false);
        stepProgress.setValue(1);
    }
    
    private boolean isPause(int contador) {
        return contador >= (TIMEPAUSE * MINUTE);
    }
    
    private boolean isStep(int contador) {
        return contador >= (TIMESTEP * MINUTE);
    }
    
    private boolean isLongPause(int contador) {
        return contador >= (TIMELONGPAUSE * MINUTE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfigCronometro;
    private javax.swing.JButton btnNextStep;
    private javax.swing.JButton btnPlayPause;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbStepNumber;
    private javax.swing.JLabel lbStepStatus;
    private javax.swing.JLabel lbTimerLongPause;
    private javax.swing.JLabel lbTimerPause;
    private javax.swing.JLabel lbTimerStep;
    private javax.swing.JLabel showTimer;
    private javax.swing.JProgressBar stepProgress;
    // End of variables declaration//GEN-END:variables
}
